### ISSUE TITLE
Navigation Bar Gesture Not Working on Android 6.0

### ISSUE THREAD

**Issue by EmmetZC** [KTachibanaM/cloudemoji#28]
I'm using Official Android 6.0 Rom on Nexus 5. Swipe-up from navigation bar didn't open the app.
Some people on the Internet suggested to try long-press home button, but that opened the Google Now page.

**Comment by sorz** [comment]
Hello,

Accroding to [this answer](https://stackoverflow.com/questions/33422213/action-assist-intent-on-marshmallow-android-6-0#answer-33434168), 
after you switch on swipe-up function on app's settings page,  an addition action is required on 6.0:

Go to `Settings -> Apps -> Default Apps -> Assist & voice input -> Assist app`,
and choose Cloud Emoticon as default Assist app.

I will try to make some improvements for 6.0, at least, tell users what need to do.

Thanks.

**Comment by sorz** [comment]
En... Anyone knows if it's possible to open `Assist & voice input` view programmatically
or pop up a message box or something to require user to choose a default assist app?

**Comment by sorz** [comment]
`com.android.settings.Settings$ManageAssistActivity`
